export const Section = {
  baseStyle: {
    container: {
      pb: 4,
    },
    imageContainer: {
      position: 'relative',
      mb: 4,
    },
    image: {
      h: '96',
      w: '100%',
      objectFit: 'cover',
      borderRadius: 'md',
    },
    imageText: {
      position: 'absolute',
      borderBottomLeftRadius: 'md',
      bottom: 0,
      bg: 'rgb(0,0,0, .6)',
      fontFamily: 'heading',
      px: 4,
      py: 2,
      borderRadius: 'tr',
      color: 'white',
      fontSize: 'xs',
    },
    heading: {
      fontSize: ['2xl', '', '', '3xl'],
      borderTop: 'none',
      mt: 0,
      pt: 0,
      mb: [4, 4, 4, 8],
      color: 'background',
      bg: 'primary',
      fontWeight: 600,
      textAlign: 'center',
      fontFamily: 'body',
      letterSpacing: 2,
      textTransform: 'uppercase',
      py: 4,
      textShadow: 0,
    },
    description: {
      fontSize: 'xs',
      color: 'dark',
      mb: 8,
      lineHeight: 5,
      maxWidth: 600,
      mx: 'auto',
      textAlign: 'center',
      fontWeight: 300,
    },
  },
  variants: {},
};
